name: Push rapidocr_web to pypi

on:
  push:
    tags:
      - v*

jobs:
  GenerateWHL_PushPyPi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Run setup.py
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install get_pypi_latest_version wheel
          pip install --upgrade setuptools

          python -m pip install --upgrade pip
          python setup.py bdist_wheel "${{ github.ref_name }}"

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPIDOCR_WEB }}
          packages_dir: dist/
